service: lambda-example

package:
  exclude:
    - test/**
    - coverage/**
    - config/**

provider:
  name: aws
  runtime: nodejs6.10
  stage: example
  region: us-east-1
  memorySize: 256
  timeout: 10
  versionFunctions: false
  environment:
    ${file(config/${opt:stage, self:provider.stage}.yml)}

functions:
  div:
    handler: lib/handler.div
    description: Return a div b for parameters a and b.
    private: false
  geoip:
    handler: lib/handler.geoip
    description: Return geo information for ip
    private: false
  now:
    handler: lib/handler.now
    description: Return current time in UTC
    private: false
  logger:
    handler: lib/handler.logger
    description: Log an Error to rollbar
    private: false
  stage:
    handler: lib/handler.stage
    description: Return current Stage
    private: false
