service: lambda-example

package:
  exclude:
    - test/**
    - coverage/**
    - config/**

provider:
  name: aws
  runtime: nodejs6.10
  stage: example
  region: us-east-1
  memorySize: 256
  timeout: 10
  versionFunctions: false
  environment:
    ${file(config/${opt:stage, self:provider.stage}.yml)}

functions:
  div:
    handler: lib/lambda.div
    description: Return a div b for parameters a and b.
    private: false
  geoip:
    handler: lib/lambda.geoip
    description: Return geo information for ip
    private: false
  now:
    handler: lib/lambda.now
    description: Return current time in UTC
    private: false
  logger:
    handler: lib/lambda.logger
    description: Log an Error to rollbar
    private: false
  stage:
    handler: lib/lambda.stage
    description: Return current Stage
    private: false
  sum:
    handler: lib/https.sum
    description: Return sum of input array
    private: false
    events:
      - http:
          path: sum
          method: GET
