swagger: '2.0'
produces:
  - application/json
info:
  title: Api Name
  version: 0.0.1
paths:
  /sum:
    get:
      consumes:
        - application/json
      description: ''
      parameters:
        - name: input
          required: true
          type: string
          format: Str
          in: query
          pattern: >-
            /!?^(|undefined|undef|null|NULL|\(null\)|nil|NIL|true|false|True|False|TRUE|FALSE|None|NaN|Infinity|\-Infinity|INF|"|'|""|''|%|_|\-|\-\-|NUL|\[object
            Object\])$/
      responses:
        default:
          description: Unexpected Error
